In [2]:
# use sequential to dribe a nn
import torch
from torch import nn
from torch.nn import functional as F

net = nn.Sequential(
    nn.Linear(20,256),# first layer
    nn.ReLU(),
    nn.Linear(256,10)
)
X = torch.rand(2,20)
net(X)

tensor([[-0.1009, -0.0407,  0.1246,  0.0582, -0.0555, -0.0764, -0.0761, -0.0391,
          0.0492,  0.0110],
        [-0.0154,  0.0865, -0.0603,  0.0951, -0.0533,  0.0984, -0.1372, -0.0331,
          0.0872, -0.1189]], grad_fn=<AddmmBackward>)

In [ ]:
# to create a block class
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.out = nn.Linear(256,10)

    def forward(self,X): #
        return self.out(F.relu(self.hidden(X)))
# we can also add sequential into our blockm
# attention: it should have a forward function

In [8]:
# params managing
net = nn.Sequential(
    nn.Linear(2,5),# first layer
    nn.ReLU(),
    nn.Linear(5,3)
)
# get params
print(net[2].state_dict()) # return a dict of params including weight and bias
print(net[2].named_parameters()) # return a generator containing named params
print(net[2].bias) # parameter class
print(net[2].bias.data)
print([(name, params.shape )for name, params in net[0].named_parameters()])

# multiple block
def block1():
    return nn.Sequential(nn.Linear(4,8),nn.ReLU(),
                         nn.Linear(8,2),nn.ReLU())
def block2():
    net = nn.Sequential()
    for i in range(4):
        net.add_module(f'module_{i}_in_block2',block1())
    return net
rgnet = nn.Sequential(block2(),nn.Linear(2,1))
print(rgnet)
# then try to get the params of the rgnet
print(rgnet.state_dict()) # output three layter params


OrderedDict([('weight', tensor([[-0.3487, -0.2946,  0.4397,  0.0554, -0.1817],
        [ 0.3711, -0.1712,  0.0006, -0.0135, -0.2769],
        [ 0.0731,  0.3509, -0.1399, -0.4341, -0.0101]])), ('bias', tensor([ 0.0704,  0.4454, -0.3070]))])
<generator object Module.named_parameters at 0x7f04250a6c10>
Parameter containing:
tensor([ 0.0704,  0.4454, -0.3070], requires_grad=True)
tensor([ 0.0704,  0.4454, -0.3070])
[('weight', torch.Size([5, 2])), ('bias', torch.Size([5]))]
Sequential(
  (0): Sequential(
    (module_0_in_block2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=2, bias=True)
      (3): ReLU()
    )
    (module_1_in_block2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=2, bias=True)
      (3): ReLU()
    )
    (module_2_in_block2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=Tr

In [13]:
# init params

def init_normal(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight,mean=0,std=0.01)
        nn.init.zeros_(m.bias)
def init_constant(m):
    if type(m) == nn.Linear:
        nn.init.constant_(m.weight,100)
        nn.init.zeros_(m.bias)

def init_custom(m):
    pass

net.apply(init_normal) # input the init function to net

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=3, bias=True)
)

In [14]:
# parameters binding
share = nn.Linear(8,8) # shared layer
net = nn.Sequential(nn.Linear(4,8),nn.ReLU(),
                    share,nn.ReLU(),
                    share,nn.ReLU(),
                    nn.Linear(8,1))

In [22]:
#customize layer

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        # self.weight=self.params todo
        self.weight2 = nn.Parameter([[1,2,3,4,5,6],[6,6,6,6,6,6]])
    def forward(self,X):
        return X-0.1

customize_layer = CenteredLayer()
print(customize_layer(torch.FloatTensor([0,0,1,2,3])))
print(customize_layer.named_parameters())



TypeError: _make_subclass(): argument 'data' (position 2) must be Tensor, not list

In [24]:
# w/r files
torch.load()
torch.save()

TypeError: load() missing 1 required positional argument: 'f'

In [37]:
# gpu

torch.cuda.device_count()
x = torch.tensor([123],device='cuda:0')
x.device

device(type='cuda', index=0)